kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: fluentd
  namespace: fluentd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: fluentd-logging
    kubernetes.io/cluster-service: 'true'
    version: v1
spec:
  selector:
    matchLabels:
      kubernetes.io/cluster-service: 'true'
      name: fluentd-logging
      version: v1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        kubernetes.io/cluster-service: 'true'
        name: fluentd-logging
        version: v1
    spec:
      restartPolicy: Always
      serviceAccountName: fluentd
      #imagePullSecrets:
        #- name: ocp-reader-pull-secret
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: fluentd
          image: fluentd:latest
          resources:
            limits:
              memory: 800Mi
            requests:
              cpu: 100m
              memory: 800Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log/
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            - name: config
              mountPath: /etc/fluent
            - name: tmp
              mountPath: /mnt/tmp
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      serviceAccount: fluentd
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/
            type: ''
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: ''
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: fluentd-logging
            defaultMode: 420
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
