apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusOperator:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    prometheusK8s:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    alertmanagerMain:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    kubeStateMetrics:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    grafana:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    telemeterClient:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    k8sPrometheusAdapter:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    openshiftStateMetrics:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
    thanosQuerier:
      nodeSelector: 
        node-role.kubernetes.io/infra: ""
      tolerations: 
      - key: "node-function"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"

