apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: engine-availability
  namespace: federated-prometheus
  labels:
    app: grafana
spec:
  customFolderName: "ocp sli reports"
  name: engine-availability.json
  json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "limit": 100,
            "name": "Annotations & Alerts",
            "showIn": 0,
            "target": {},
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 39,
      "links": [],
      "panels": [
        {
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {},
              "decimals": 2,
              "mappings": [],
              "noValue": "0",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "dark-red",
                    "value": null
                  },
                  {
                    "color": "dark-green",
                    "value": 98
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 11,
            "w": 6,
            "x": 0,
            "y": 0
          },
          "id": 3,
          "interval": "1d",
          "options": {
            "orientation": "auto",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "/^\\{\\}$/",
              "values": false
            },
            "showThresholdLabels": false,
            "showThresholdMarkers": true
          },
          "pluginVersion": "7.3.10",
          "repeat": null,
          "targets": [
            {
              "expr": "(sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =\"STATUS_PROBE_SMOKETEST\"  and success = \"true\" [1d])) / sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =\"STATUS_PROBE_SMOKETEST\" [1d]))) * 100.00",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Success Rate",
          "transformations": [],
          "type": "gauge"
        },
        {
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {},
              "mappings": [],
              "noValue": "0",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 2,
            "w": 2,
            "x": 6,
            "y": 0
          },
          "id": 4,
          "interval": "1d",
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": [
                "sum"
              ],
              "fields": "/^\\{\\}$/",
              "values": false
            },
            "textMode": "value"
          },
          "pluginVersion": "7.3.10",
          "targets": [
            {
              "expr": "sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event =\"STATUS_PROBE_SMOKETEST\" and success = \"true\" [1d]))",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": "7d",
          "timeShift": null,
          "title": "Success",
          "transparent": true,
          "type": "stat"
        },
        {
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {},
              "mappings": [],
              "noValue": "0",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 2,
            "w": 2,
            "x": 13,
            "y": 0
          },
          "id": 5,
          "interval": "1d",
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": [
                "sum"
              ],
              "fields": "/^\\{\\}$/",
              "values": false
            },
            "textMode": "value"
          },
          "pluginVersion": "7.3.10",
          "targets": [
            {
              "expr": "sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event =\"STATUS_PROBE_SMOKETEST\"  and success != \"true\"  [1d]))",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": "7d",
          "timeShift": null,
          "title": "Failures",
          "transformations": [],
          "transparent": true,
          "type": "stat"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {},
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 11,
            "w": 8,
            "x": 15,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 12,
          "interval": "1d",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": false
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (success) (count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event =\"STATUS_PROBE_SMOKETEST\"  [1d]))",
              "legendFormat": "{{success}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": "7d",
          "timeRegions": [],
          "timeShift": null,
          "title": "",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": "0",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": true,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {},
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 9,
            "x": 6,
            "y": 2
          },
          "hiddenSeries": false,
          "id": 11,
          "interval": "1d",
          "legend": {
            "alignAsTable": false,
            "avg": false,
            "current": false,
            "hideEmpty": false,
            "hideZero": false,
            "max": false,
            "min": false,
            "rightSide": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": false,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": false
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (success) (count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event = \"STATUS_PROBE_SMOKETEST\" [1d]))",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": "7d",
          "timeRegions": [],
          "timeShift": null,
          "title": "",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": "",
              "logBase": 1,
              "max": null,
              "min": "0",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": null,
                "filterable": true
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "event"
                },
                "properties": [
                  {
                    "id": "custom.filterable",
                    "value": true
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 10,
            "w": 23,
            "x": 0,
            "y": 11
          },
          "id": 2,
          "interval": "",
          "options": {
            "frameIndex": 1,
            "showHeader": true,
            "sortBy": [
              {
                "desc": false,
                "displayName": "Log Message"
              }
            ]
          },
          "pluginVersion": "7.3.10",
          "targets": [
            {
              "expr": "{container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =\"STATUS_PROBE_SMOKETEST\"  ",
              "hide": false,
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": " ",
          "transformations": [
            {
              "id": "labelsToFields",
              "options": {}
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "isAudit_extracted": true,
                  "line": true,
                  "tsNs": true
                },
                "indexByName": {
                  "cluster_name": 7,
                  "container_name": 1,
                  "duration": 4,
                  "err_code": 13,
                  "event": 8,
                  "id": 11,
                  "isAudit": 5,
                  "isAudit_extracted": 2,
                  "line": 10,
                  "logName": 3,
                  "session": 9,
                  "success": 6,
                  "ts": 0,
                  "tsNs": 12
                },
                "renameByName": {
                  "ts": "Timestamp"
                }
              }
            }
          ],
          "type": "table"
        }
      ],
      "refresh": false,
      "schemaVersion": 26,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "nowDelay": "",
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "Engine Availability",
      "uid": "rxVPcdnnz",
      "version": 26
    }