{
 "title": "Engine Latency (K8s) - GPU based",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gpu", "label": "GPU", "query": "true" }
  ]
 },
 "panels": [
  {
   "title": "Overall SLI %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "( sum(count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and event_status = \"success\" and engine_gpu = \"$gpu\" and timeToState <= 360 [1d]) ) / sum(count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu = \"$gpu\" and timeToState <= 360 [1d]) ) )* 100.00"
    }
   ]
  },
  {
   "title": "Average start up time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu = \"$gpu\" and timeToState <= 360 | unwrap timeToState [1d]) )"
    }
   ]
  },
  {
   "title": "Minimum time to start (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(min_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu  = \"$gpu\" and timeToState <= 360 | unwrap timeToState [1d]) )"
    }
   ]
  },
  {
   "title": "Maximum time to start (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu  = \"$gpu\" and timeToState <= 360 | unwrap timeToState [1d]) )"
    }
   ]
  },
  {
   "title": "Total count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu  = \"$gpu\" and timeToState <= 360 [1d]) )"
    }
   ]
  },
  {
   "title": "Average Startup timestamp (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (engineName) (avg_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu  = \"$gpu\" and timeToState  <= 360 | unwrap timeToState [1d]))",
     "legendFormat": "{{engineName}}"
    }
   ]
  },
  {
   "title": "SLI Incidents ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (engineName) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu  = \"$gpu\" and timeToState  <= 360 [1d]))",
     "legendFormat": "{{engineName}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (engineName) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" and engine_gpu = \"$gpu\" and timeToState  <= 360 [1d]))",
     "legendFormat": "{{engineName}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | engine_provider = \"kubernetes\" and event = \"INSTANCE_RUNNING\" engine_gpu  = \"$gpu\" and timeToState <= 360"
    }
   ]
  }
 ]
}