{
 "title": "Engine Availability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =\"STATUS_PROBE_SMOKETEST\"  and success = \"true\" [1d])) / sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =\"STATUS_PROBE_SMOKETEST\" [1d]))) * 100.00"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event =\"STATUS_PROBE_SMOKETEST\" and success = \"true\" [1d]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event =\"STATUS_PROBE_SMOKETEST\"  and success != \"true\"  [1d]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event =\"STATUS_PROBE_SMOKETEST\"  [1d]))",
     "legendFormat": "{{success}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json |  event = \"STATUS_PROBE_SMOKETEST\" [1d]))"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =\"STATUS_PROBE_SMOKETEST\"  "
    }
   ]
  }
 ]
}