{
 "title": "Engine Reliability (K8s)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventflag",
    "label": "Event",
    "query": "INSTANCE_SUCCEEDED, INSTANCE_FAILED"
   }
  ]
 },
 "panels": [
  {
   "title": "$eventflag by Engine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (engineName) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event = \"$eventflag\"  and engine_provider = \"kubernetes\" [1d]))",
     "legendFormat": "{{engineName}}"
    }
   ]
  },
  {
   "title": "$eventflag by Engine",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (engineName) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event = \"$eventflag\" and engine_provider = \"kubernetes\" [1d]))"
    }
   ]
  },
  {
   "title": "% by Engine",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "((sum by (engineName) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event = \"$eventflag\" and engine_provider = \"kubernetes\" [1d]))) /\r\n(sum by (engineName) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event =~ \"INSTANCE_SUCCEEDED|INSTANCE_FAILED\" and engine_provider = \"kubernetes\" [1d]))) ) * 100.00"
    }
   ]
  },
  {
   "title": "$eventflag by Userid",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (userId) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event = \"$eventflag\" and engine_provider = \"kubernetes\" [1d]))"
    }
   ]
  },
  {
   "title": "% by Userid",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "((sum by (userId) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event = \"$eventflag\" and engine_provider = \"kubernetes\" [1d]))) / (sum by (userId) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event =~ \"INSTANCE_SUCCEEDED|INSTANCE_FAILED\" and engine_provider = \"kubernetes\" [1d])))) * 100.00"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event = \"$eventflag\" and engine_provider = \"kubernetes\""
    }
   ]
  }
 ]
}