apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: filestore-usage
  namespace: federated-prometheus
  labels:
    app: grafana
spec:
  customFolderName: "ocp sli reports"
  name: filestore-usage.json
  json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "limit": 100,
            "name": "Annotations & Alerts",
            "showIn": 0,
            "target": {},
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 33,
      "links": [],
      "panels": [
        {
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": null,
                "filterable": true
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 16,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "interval": "",
          "options": {
            "frameIndex": 1,
            "showHeader": true,
            "sortBy": [
              {
                "desc": false,
                "displayName": "Log Message"
              }
            ]
          },
          "pluginVersion": "7.3.10",
          "targets": [
            {
              "expr": "{isAudit=\"true\", container_name=\"ocp-file-service\"} | json | event = \"UPLOAD_FILE\" and event_status = \"success\" and pvUsage > 0",
              "hide": false,
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": " ",
          "transformations": [
            {
              "id": "labelsToFields",
              "options": {}
            },
            {
              "id": "organize",
              "options": {}
            }
          ],
          "type": "table"
        }
      ],
      "refresh": false,
      "schemaVersion": 26,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "nowDelay": "",
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "Filestore Usage",
      "uid": "YQpn4d7nz",
      "version": 13
    }