{
 "title": "Filestore startup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event =~ \".*FILESTORE_READY.*\" and status = \"success\" [1d]))) / (sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event =~ \".*FILESTORE_READY.*\" [1d]))) * 100.00"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event =~ \".*FILESTORE_READY.*\" and status = \"success\" [1d]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event =~ \".*FILESTORE_READY.*\" and status != \"success\" [1d]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" [1d]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" [1d]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time( {isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" | unwrap latency | __error__ = \"\"  [1d]) by (event)",
     "legendFormat": "max"
    },
    {
     "expr": "quantile_over_time(.10, {isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" | unwrap latency | __error__ = \"\"  [1d]) by (event)",
     "legendFormat": "p10"
    },
    {
     "expr": "quantile_over_time(.90, {isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" | unwrap latency | __error__ = \"\"  [1d]) by (event)",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile_over_time(.50, {isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" | unwrap latency | __error__ = \"\"  [1d]) by (event)",
     "legendFormat": "median"
    },
    {
     "expr": "min_over_time({isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event =~ \".*FILESTORE_READY.*\" | unwrap latency | __error__ = \"\"  [1d]) by (event)",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event =~ \".*FILESTORE_READY.*\""
    }
   ]
  }
 ]
}