apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: filestores
  namespace: federated-prometheus
  labels:
    app: grafana
spec:
  customFolderName: "ocp sli reports"
  name: filestores.json
  json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "limit": 100,
            "name": "Annotations & Alerts",
            "showIn": 0,
            "target": {},
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 34,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "{jsonPayload_success=\"true\"}"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "success"
                  }
                ]
              }
            ]
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 11,
          "interval": "1d",
          "legend": {
            "alignAsTable": false,
            "avg": false,
            "current": false,
            "hideZero": false,
            "max": false,
            "min": false,
            "rightSide": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "success",
              "color": "#73BF69"
            },
            {
              "alias": "failed",
              "color": "#C4162A"
            },
            {
              "alias": "No status",
              "color": "#C4162A"
            }
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (event_status ) (count_over_time({isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event = \"POST_FILESTORE\"  [1d]))",
              "hide": false,
              "legendFormat": "{{event_status}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": "7d",
          "timeRegions": [],
          "timeShift": null,
          "title": "",
          "tooltip": {
            "shared": false,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": null,
                "filterable": true
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 13,
            "w": 24,
            "x": 0,
            "y": 9
          },
          "id": 2,
          "interval": "",
          "options": {
            "frameIndex": 0,
            "showHeader": true,
            "sortBy": [
              {
                "desc": true,
                "displayName": "Log Message"
              }
            ]
          },
          "pluginVersion": "7.3.10",
          "targets": [
            {
              "expr": "{isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | event = \"POST_FILESTORE\" ",
              "hide": false,
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": " ",
          "transformations": [
            {
              "id": "labelsToFields",
              "options": {}
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "line": true,
                  "timestamp": true,
                  "tsNs": true
                },
                "indexByName": {
                  "cloud_provider": 11,
                  "cluster_name": 12,
                  "container_name": 14,
                  "event": 3,
                  "event_status": 4,
                  "id": 21,
                  "isAudit": 15,
                  "isAudit_extracted": 18,
                  "latency": 2,
                  "line": 20,
                  "logName": 19,
                  "name": 1,
                  "namespace_name": 13,
                  "pod_id": 10,
                  "project_id": 7,
                  "region": 16,
                  "session": 0,
                  "severity": 8,
                  "size": 9,
                  "timestamp": 6,
                  "ts": 5,
                  "tsNs": 22,
                  "zone": 17
                },
                "renameByName": {}
              }
            }
          ],
          "transparent": true,
          "type": "table"
        }
      ],
      "refresh": false,
      "schemaVersion": 26,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "nowDelay": "",
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "Filestores",
      "uid": "orX5VO77z",
      "version": 14
    }