{
 "title": "License Probe",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=~\".*LICENSE.*\"  and success = \"true\"  [1d])) / sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=~\".*LICENSE.*\" [1d]))) * 100.00"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=~\".*LICENSE.*\"  and success = \"true\" and event!~\".*REQUEST_STATS.*\" and jsonPayload_event!~\".*STATUS_PROBE_QUOTA_CHECK.*\" [1d]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=~\".*LICENSE.*\"  and success != \"true\" and event!~\".*REQUEST_STATS.*\" and event!~\".*STATUS_PROBE_QUOTA_CHECK.*\" [1d]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=~\".*LICENSE.*\"  and event!~\".*REQUEST_STATS.*\" and event!~\".*STATUS_PROBE_QUOTA_CHECK.*\" [1d]))",
     "legendFormat": "{{success}}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (count_over_time({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=~\".*LICENSE.*\"  and event!~\".*REQUEST_STATS.*\" and event!~\".*STATUS_PROBE_QUOTA_CHECK.*\" [1d]))"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event =~\".*LICENSE.*\"  "
    }
   ]
  }
 ]
}