{
 "title": "OCP Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OCP Session Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {isAudit=\"true\", container_name=\"ocp-session-service\"} | json | name=~\"status-probe.*\"  |  unwrap latency | __error__ =\"\" [5m]) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "OCP Instance Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | name!~\"status-probe.*\"  |  unwrap latency | __error__ =\"\" [5m]) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "OCP File Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {isAudit=\"true\", container_name=\"ocp-file-service\"} | json | name!~\"status-probe.*\"  |  unwrap latency | __error__ = \"\" [5m]) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "OCP File Store Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {isAudit=\"true\", container_name=\"ocp-filestore-service\"} | json | name!~\"status-probe.*\"  |  unwrap latency | __error__ = \"\" [5m]) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "OCP Message Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {isAudit=\"true\", container_name=\"ocp-message-service\"} | json | name!~\"status-probe.*\"  |  unwrap latency | __error__ = \"\" [5m]) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  }
 ]
}