{
 "title": "OCP Cluster Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OCP Service Node Pool Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_NODE_POOL_SIZE\" and event_status=\"success\" and isCpuNode = \"false\" | unwrap utilization | __error__ = \"\" [5m]) by (nodePool)",
     "legendFormat": "{{nodePool}}"
    }
   ]
  },
  {
   "title": "OCP Service Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_NODE_POOL_SIZE\" and event_status=\"success\" and nodePool=~\"default-pool-ocpv1.*\"  [5m])) by (nodePool)"
    }
   ]
  },
  {
   "title": "K8 Service Node Pool Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_NODE_POOL_SIZE\" and event_status=\"success\" and nodePool=\"default-pool\" | unwrap utilization | __error__ = \"\" [5m]) by (nodePool)",
     "legendFormat": "{{nodePool}}"
    }
   ]
  },
  {
   "title": "K8 Service Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(count_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_NODE_POOL_SIZE\" and event_status=\"success\" and nodePool=\"default-pool\" [5m])) "
    }
   ]
  },
  {
   "title": "Engine Pools Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_NODE_POOL_SIZE\" and event_status=\"success\" and nodePool!~\"default-pool.*\" | unwrap utilization | __error__ = \"\" [5m]) by (nodePool)",
     "legendFormat": "{{nodePool}}"
    }
   ]
  },
  {
   "title": "Engine Pools Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(count_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_NODE_POOL_SIZE\" and event_status=\"success\" and nodePool!~\"default-pool.*\" [5m])) by (nodePool)",
     "legendFormat": "{{nodePool}}"
    }
   ]
  }
 ]
}