{
 "title": "OCP Probes",
 "time": { "from": "2021-08-05T14:01:00.611Z", "to": "2021-08-05T14:01:59.886Z" },
 "panels": [
  {
   "title": "Pulse Smoketest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (count_over_time({isAudit=\"true\", container_name =\"ocp-status-probe\"} | json | success=\"true\" and event=\"STATUS_PROBE_SMOKETEST\" [1m]))"
    }
   ]
  },
  {
   "title": "Pulse Quota Check (K8s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (count_over_time({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [1m]))"
    }
   ]
  },
  {
   "title": "Pulse Failed Engines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (engine_name) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | (event=\"INSTANCE_FAILED\" and errorMessage!=\"QuotaExceeded\")  [5m]))"
    }
   ]
  },
  {
   "title": "Pulse Succeeded Engines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (engine_name) (count_over_time({isAudit=\"true\", container_name=\"ocp-instance-service\"} | json | event=\"INSTANCE_SUCCEEDED\"  [1m]))"
    }
   ]
  }
 ]
}