{
 "title": "OCP Availability SLI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OCP Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=\"STATUS_PROBE_SMOKETEST\" and success =\"true\" [1d])) /\r\nsum(rate({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=\"STATUS_PROBE_SMOKETEST\" [1d])))",
     "legendFormat": "availability"
    },
    { "expr": "0.98", "legendFormat": "goal" }
   ]
  },
  {
   "title": "OCP Instance Service Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate({container_name=\"ocp-instance-service\", isAudit=\"true\"} | json | event_status =\"success\" [1d])) / sum(rate({container_name=\"ocp-instance-service\", isAudit=\"true\"}  [1d])))",
     "legendFormat": "availability"
    },
    { "expr": "0.993", "legendFormat": "goal" }
   ]
  },
  {
   "title": "OCP Message Service Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(count_over_time({container_name=\"ocp-message-service\", isAudit=\"true\"} | json |  event_status=\"success\" [1d])) / sum(count_over_time({container_name=\"ocp-message-service\", isAudit=\"true\"}  [1d])))",
     "legendFormat": "availability"
    },
    { "expr": "0.975", "legendFormat": "goal" }
   ]
  },
  {
   "title": "OCP Filestore Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " (sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event_status = \"success\"  [1d])) / \r\nsum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"}  [1d]))) ",
     "legendFormat": "availability"
    },
    { "expr": "0.993", "legendFormat": "goal" }
   ]
  },
  {
   "title": "OCP Filestore Startup Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event=\"FILESTORE_READY\" and event_status = \"success\" and latency > 30000  [1d])) / sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event=\"FILESTORE_READY\" and  latency > 30000 [1d])) ) ",
     "legendFormat": "latency"
    },
    { "expr": "0.975", "legendFormat": "goal" }
   ]
  }
 ]
}