{
 "title": "OCP Project Utilization",
 "time": { "from": "2021-08-05T18:07:44.447Z", "to": "2021-08-05T18:59:21.506Z" },
 "panels": [
  {
   "title": "Resource Utilization By Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate({isAudit=\"true\", container=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [5m])) by (metric, region)",
     "legendFormat": "{{metric}}-{{region}}"
    }
   ]
  },
  {
   "title": "Resource Utilzation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Resource Usage By Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate({isAudit=\"true\", container_name=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [5m])) by (metric, region)",
     "legendFormat": "{{metric}}-{{region}}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate({isAudit=\"true\", logName=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Resource Limit By Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate({isAudit=\"true\", logName=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [5m])) by (metric, region)",
     "legendFormat": "{{metric}}-{{region}}"
    }
   ]
  },
  {
   "title": "Resource Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate({isAudit=\"true\", logName=\"ocp-monitoring-daemon\"} | json | event=\"CHECK_QUOTA\" [5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  }
 ]
}