apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: ocp-availability-sli
  namespace: federated-prometheus
  labels:
    app: grafana
spec:
  customFolderName: "ocp"
  name: ocp-availability-sli.json
  json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 27,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": null,
                "filterable": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 2,
          "interval": "12h",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {}
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "(sum(rate({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=\"STATUS_PROBE_SMOKETEST\" and success =\"true\" [1d])) /\r\nsum(rate({container_name=\"ocp-status-probe\", isAudit=\"true\"} | json | event=\"STATUS_PROBE_SMOKETEST\" [1d])))",
              "legendFormat": "availability",
              "refId": "A"
            },
            {
              "expr": "0.98",
              "legendFormat": "goal",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": "30d",
          "timeRegions": [
            {
              "colorMode": "background6",
              "fill": true,
              "fillColor": "rgba(234, 112, 112, 0.12)",
              "line": false,
              "lineColor": "rgba(237, 46, 24, 0.60)",
              "op": "time"
            }
          ],
          "timeShift": null,
          "title": "OCP Availability",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "transformations": [],
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 13,
            "x": 0,
            "y": 7
          },
          "hiddenSeries": false,
          "id": 9,
          "interval": "12h",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "(sum(rate({container_name=\"ocp-instance-service\", isAudit=\"true\"} | json | event_status =\"success\" [1d])) / sum(rate({container_name=\"ocp-instance-service\", isAudit=\"true\"}  [1d])))",
              "legendFormat": "availability",
              "refId": "C"
            },
            {
              "expr": "0.993",
              "legendFormat": "goal",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": "30d",
          "timeRegions": [],
          "timeShift": null,
          "title": "OCP Instance Service Availability",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 11,
            "x": 13,
            "y": 7
          },
          "hiddenSeries": false,
          "id": 11,
          "interval": "12h",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "(sum(count_over_time({container_name=\"ocp-message-service\", isAudit=\"true\"} | json |  event_status=\"success\" [1d])) / sum(count_over_time({container_name=\"ocp-message-service\", isAudit=\"true\"}  [1d])))",
              "legendFormat": "availability",
              "refId": "C"
            },
            {
              "expr": "0.975",
              "legendFormat": "goal",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": "30d",
          "timeRegions": [],
          "timeShift": null,
          "title": "OCP Message Service Availability",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 13,
            "x": 0,
            "y": 14
          },
          "hiddenSeries": false,
          "id": 4,
          "interval": "12h",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": false
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": " (sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event_status = \"success\"  [1d])) / \r\nsum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"}  [1d]))) ",
              "legendFormat": "availability",
              "refId": "A"
            },
            {
              "expr": "0.993",
              "legendFormat": "goal",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": "30d",
          "timeRegions": [],
          "timeShift": null,
          "title": "OCP Filestore Availability",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "loki",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 11,
            "x": 13,
            "y": 14
          },
          "hiddenSeries": false,
          "id": 6,
          "interval": "12h",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.3.10",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "(sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event=\"FILESTORE_READY\" and event_status = \"success\" and latency > 30000  [1d])) / sum(count_over_time({container_name=\"ocp-filestore-service\", isAudit=\"true\"} | json | event=\"FILESTORE_READY\" and  latency > 30000 [1d])) ) ",
              "legendFormat": "latency",
              "refId": "B"
            },
            {
              "expr": "0.975",
              "legendFormat": "goal",
              "refId": "C"
            }
          ],
          "thresholds": [],
          "timeFrom": "30d",
          "timeRegions": [],
          "timeShift": null,
          "title": "OCP Filestore Startup Latency",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "refresh": false,
      "schemaVersion": 26,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "OCP Availability SLI",
      "uid": "l3hZmuMnk",
      "version": 31
    }