{
 "title": "Sessions",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Session POST Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflowName) (count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} | json | event = \"POST_SESSION\" and event_status = \"success\" [1d]))"
    }
   ]
  },
  {
   "title": "Session POST Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (workflowName) (avg_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} | json | event = \"POST_SESSION\" | unwrap latency [1d]))"
    }
   ]
  },
  {
   "title": "Total Success By Workflow",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (workflowName) (count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} |json| event = \"POST_SESSION\" and event_status = \"success\" [1d]))"
    }
   ]
  },
  {
   "title": "Success Rate By Workflow",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (workflowName) (count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} |json| event = \"POST_SESSION\" and event_status = \"success\" [1d]))) / (sum by (workflowName)(count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} |json| event = \"POST_SESSION\"  [1d]))) * 100.00"
    }
   ]
  },
  {
   "title": "Success By UserId",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (userId) (count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} |json| event = \"POST_SESSION\" and event_status = \"success\" [1d]))"
    }
   ]
  },
  {
   "title": "Success By UserId",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "((sum by (userId) (count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} |json| event = \"POST_SESSION\" and event_status = \"success\" [1d]))) / (sum by (userId) (count_over_time({isAudit=\"true\", container_name=\"ocp-session-service\"} |json| event = \"POST_SESSION\" [1d]))) ) * 100.00"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{isAudit=\"true\", container_name=\"ocp-session-service\"} | json | event = \"POST_SESSION\""
    }
   ]
  }
 ]
}