apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: federated-prometheus-admins
  namespace: federated-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: federated-prometheus-admins
