apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-k8s-proxy-secret-creator
  namespace: federated-prometheus
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.6.0
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/creator

              echo "Creating a secret to hold the Grafana oauth session key for encrypting requests "
              sleep 3

              export KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c43 | base64)
              cat <<EOF | oc apply -f -
              kind: Secret
              apiVersion: v1
              metadata:
                name: grafana-k8s-proxy
                namespace: federated-prometheus
              data:
                session_secret: $KEY
              type: Opaque

              EOF

          imagePullPolicy: Always
          name: grafana-k8s-proxy-secret-creator
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: proxy-secret-creator
      serviceAccountName: proxy-secret-creator 
      terminationGracePeriodSeconds: 30

