apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-secret-creator
  namespace: federated-prometheus 
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.6.0
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/creator

              echo "Creating Prometheus App account to allow local prometheus to authenticated to federated prometheus."
              sleep 3

              
              if (oc -n federated-prometheus get secrets  | grep app-prometheus-bearer-token); then

              echo "app-prometheus-bearer-token already exists"
 
              else
  
              oc -n federated-prometheus create secret generic app-prometheus-bearer-token --from-literal=app-prometheus-bearer-token=$(oc -n openshift-monitoring serviceaccounts get-token prometheus-k8s)

              fi;
              

          imagePullPolicy: Always
          name: prometheus-secret-creator 
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: prometheus-secret-creator
      serviceAccountName: prometheus-secret-creator
      terminationGracePeriodSeconds: 30


