apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-istio-system-secret-creator
  namespace: federated-prometheus 
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.6.0
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/creator

              echo "Creating Prometheus App account to allow local prometheus to authenticated to federated prometheus."
              sleep 3
        
              export PASSWORD=$(oc -n istio-system get secret  htpasswd -o jsonpath={.data.rawPassword} )
              cat <<EOF | oc apply -f -  
              kind: Secret
              apiVersion: v1
              metadata:
                name: istio-prometheus-password
                namespace: federated-prometheus
              data:
                istio-prometheus-password: >-
                  $PASSWORD
              type: Opaque   

              EOF
  
          imagePullPolicy: Always
          name: prometheus-istio-system-secret-creator 
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: istio-secret-creator
      serviceAccountName: istio-secret-creator 
      terminationGracePeriodSeconds: 30
