apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-secret-creator 
  namespace: federated-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-sa-getter 
rules:
  - apiGroups:
      - "" 
      - rbac.authorization.k8s.io
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list 
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-secret-creators
  namespace: federated-prometheus 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-secret-creator
subjects:
  - kind: ServiceAccount
    name: prometheus-secret-creator 
    namespace: federated-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-sa-getters
  namespace: openshift-monitoring 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-sa-getter
subjects:
  - kind: ServiceAccount
    name: prometheus-secret-creator 
    namespace: federated-prometheus

