apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-secret-creator
  namespace: federated-prometheus
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-secret-creator 
  namespace: federated-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-secret-creators
  namespace: federated-prometheus 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy-secret-creator
subjects:
  - kind: ServiceAccount
    name: proxy-secret-creator 
    namespace: federated-prometheus
---

