apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - loki-namespace.yml
  - loki-build.yaml  
  - loki-config-configmap.yml
  - loki-rules.yml  
  - loki-serviceaccount.yml
  - loki-serviceaccount-bucket-creator.yml
  - loki-role-binding.yml
  - loki-bucket-creator-job.yaml
  - loki-data-pvc.yml
  - loki-deployment.yml
  - loki-service.yml
  - loki-route.yml
  - loki-admins-rolebinding.yaml
  - loki-developers-rolebinding.yaml
  
