apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: loki
  labels:
    app: loki
data: 
  loki-rule.yaml: |
    groups:
      - name: availability_failure
        rules:
          - alert: ocp-availability
            expr: |
              sum(count_over_time({container_name="ocp-status-probe", isAudit="true"} | json | jsonPayload_event="STATUS_PROBE_SMOKETEST" and jsonPayload_success ="false" [5m])) > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              title: "TESTING: OCP Availability Alert"
              description: "TESTING: OCP availability failures occured, needs attention"
