apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: loki-bucket-creator 
  namespace: loki
rules:
  - apiGroups:
      - objectbucket.io
    resources:
      - events
      - objectbucket
      - objectbucketclaims
      - endpoints
  

    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-bucket-creator 
  namespace: loki 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-bucket-creator 
subjects:
  - kind: ServiceAccount
    name: loki-bucket-creator 
    namespace: loki
