---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/display-name: loki
  name: loki
  namespace: loki
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: loki
  namespace: loki
spec:
  nodeSelector: null
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: >-
        https://<repo_url>/ocp-gitops-infra-config
      ref: master
    contextDir: manifests/loki
    sourceSecret:
      name: ocp-gitops-config-git
  output:
    to:
      kind: ImageStreamTag
      name: loki:latest
  triggers:
    - type: ConfigChange
  runPolicy: Serial
