# OCS Operator (Namespace + Operator Group + Subscription)
---
# Create openshift-storage namespace.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: nfd-operator
spec: {}
